-- MySQL Script generated by MySQL Workbench
-- 05/06/15 09:14:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecbook_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecbook_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecbook_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecbook_db` ;

-- -----------------------------------------------------
-- Table `ecbook_db`.`benutzergruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`benutzergruppe` (
  `bg_id` INT(11) NOT NULL DEFAULT 10,
  `bg_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`bg_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`lehrer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`lehrer` (
  `l_lehrerid` INT(11) NOT NULL,
  `l_istklassenvorstand` TINYINT(1) NOT NULL,
  `l_vorname` VARCHAR(45) NOT NULL,
  `l_nachname` VARCHAR(45) NOT NULL,
  `l_geburtsdatum` DATE NOT NULL,
  `l_bg_id` INT(11) NOT NULL DEFAULT 10,
  PRIMARY KEY (`l_lehrerid`),
  INDEX `fk_lehrer_benutzergruppe1_idx` (`l_bg_id` ASC),
  CONSTRAINT `fk_lehrer_benutzergruppe1`
    FOREIGN KEY (`l_bg_id`)
    REFERENCES `ecbook_db`.`benutzergruppe` (`bg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`abteilung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`abteilung` (
  `abt_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `abt_kuerzel` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `abt_vorstand` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `l_lehrerid` INT(11) NOT NULL,
  PRIMARY KEY (`abt_bezeichnung`),
  INDEX `fk_Abteilung_Lehrer1_idx` (`l_lehrerid` ASC),
  CONSTRAINT `fk_Abteilung_Lehrer1`
    FOREIGN KEY (`l_lehrerid`)
    REFERENCES `ecbook_db`.`lehrer` (`l_lehrerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`eltern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`eltern` (
  `e_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `e_vorname` VARCHAR(45) NOT NULL,
  `e_nachname` VARCHAR(45) NOT NULL,
  `e_geburtsdatum` DATE NOT NULL,
  `e_bg_id` INT(11) NOT NULL DEFAULT 30,
  PRIMARY KEY (`e_id`),
  INDEX `fk_eltern_benutzergruppe1_idx` (`e_bg_id` ASC),
  CONSTRAINT `fk_eltern_benutzergruppe1`
    FOREIGN KEY (`e_bg_id`)
    REFERENCES `ecbook_db`.`benutzergruppe` (`bg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`schulform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`schulform` (
  `schf_id` INT(11) NOT NULL,
  `schf_zweig` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `schf_modulanforderung` TINYINT(1) NOT NULL,
  PRIMARY KEY (`schf_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`klasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`klasse` (
  `k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `k_jahrgang` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_abschlussjahr` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_schueleranzahl` INT(11) NULL DEFAULT NULL,
  `k_abt_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `k_semester` TIMESTAMP NULL DEFAULT NULL,
  `schf_id` INT(11) NOT NULL,
  PRIMARY KEY (`k_name`),
  INDEX `fk_Klasse_Abteilung1_idx` (`k_abt_bezeichnung` ASC),
  INDEX `fk_Klasse_Schulform1_idx` (`schf_id` ASC),
  CONSTRAINT `fk_Klasse_Abteilung1`
    FOREIGN KEY (`k_abt_bezeichnung`)
    REFERENCES `ecbook_db`.`abteilung` (`abt_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klasse_Schulform1`
    FOREIGN KEY (`schf_id`)
    REFERENCES `ecbook_db`.`schulform` (`schf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`schueler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`schueler` (
  `s_schuelernummer` INT(11) NOT NULL,
  `s_religionsbekenntnis` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `s_istklassensprecher` TINYINT(1) NOT NULL,
  `k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `e_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `s_vorname` VARCHAR(45) NOT NULL,
  `s_nachname` VARCHAR(45) NOT NULL,
  `s_geburtsdatum` DATE NOT NULL,
  `s_bg_id` INT(11) NOT NULL DEFAULT 20,
  PRIMARY KEY (`s_schuelernummer`),
  INDEX `fk_Schueler_Klasse1_idx` (`k_name` ASC),
  INDEX `fk_Schueler_Eltern1_idx` (`e_id` ASC),
  INDEX `fk_schueler_benutzergruppe1_idx` (`s_bg_id` ASC),
  CONSTRAINT `fk_Schueler_Eltern1`
    FOREIGN KEY (`e_id`)
    REFERENCES `ecbook_db`.`eltern` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schueler_Klasse1`
    FOREIGN KEY (`k_name`)
    REFERENCES `ecbook_db`.`klasse` (`k_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schueler_benutzergruppe1`
    FOREIGN KEY (`s_bg_id`)
    REFERENCES `ecbook_db`.`benutzergruppe` (`bg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`unterrichtsfach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`unterrichtsfach` (
  `uf_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `uf_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `uf_jahrgang` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `uf_stundenanzahlprowoche` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`uf_bezeichnung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`fehlstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`fehlstunde` (
  `fs_datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fs_grund` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `s_schuelernummer` INT(11) NOT NULL,
  `uf_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  PRIMARY KEY (`fs_datum`),
  INDEX `fk_Fehlstunde_Schueler1_idx` (`s_schuelernummer` ASC),
  INDEX `fk_Fehlstunde_Unterrichtsfach1_idx` (`uf_bezeichnung` ASC),
  CONSTRAINT `fk_Fehlstunde_Schueler1`
    FOREIGN KEY (`s_schuelernummer`)
    REFERENCES `ecbook_db`.`schueler` (`s_schuelernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fehlstunde_Unterrichtsfach1`
    FOREIGN KEY (`uf_bezeichnung`)
    REFERENCES `ecbook_db`.`unterrichtsfach` (`uf_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`krankmeldung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`krankmeldung` (
  `km_id` INT(11) NOT NULL,
  `km_datum` TIMESTAMP NULL DEFAULT NULL,
  `km_unterschrift` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `s_schuelernummer` INT(11) NOT NULL,
  PRIMARY KEY (`km_id`),
  INDEX `fk_Krankmeldung_Schueler1_idx` (`s_schuelernummer` ASC),
  CONSTRAINT `fk_Krankmeldung_Schueler1`
    FOREIGN KEY (`s_schuelernummer`)
    REFERENCES `ecbook_db`.`schueler` (`s_schuelernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`unterrichtsstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`unterrichtsstunde` (
  `us_id` INT(11) NOT NULL,
  `us_std_datum` DATE NOT NULL,
  `us_stunde` INT(11) NOT NULL,
  `us_kurzbezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `us_raum` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `us_thema` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `k_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  `l_lehrerid` INT(11) NOT NULL,
  `uf_bezeichnung` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NOT NULL,
  PRIMARY KEY (`us_id`),
  INDEX `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1_idx` (`k_name` ASC),
  INDEX `fk_Unterrichtsfach in der Unterrichtsstunde_Lehrer1_idx` (`l_lehrerid` ASC),
  INDEX `fk_Unterrichtsstunde_Unterrichtsfach1_idx` (`uf_bezeichnung` ASC),
  CONSTRAINT `fk_Unterrichtsfach in der Unterrichtsstunde_Lehrer1`
    FOREIGN KEY (`l_lehrerid`)
    REFERENCES `ecbook_db`.`lehrer` (`l_lehrerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unterrichtsstunde_Unterrichtsfach1`
    FOREIGN KEY (`uf_bezeichnung`)
    REFERENCES `ecbook_db`.`unterrichtsfach` (`uf_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1`
    FOREIGN KEY (`k_name`)
    REFERENCES `ecbook_db`.`klasse` (`k_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


-- -----------------------------------------------------
-- Table `ecbook_db`.`pruefung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbook_db`.`pruefung` (
  `p_datum` DATE NOT NULL,
  `p_uhrzeit` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_estonian_ci' NULL DEFAULT NULL,
  `uf_id` INT(11) NOT NULL,
  PRIMARY KEY (`p_datum`),
  INDEX `fk_Prüfungen_Unterrichtsstunde1_idx` (`uf_id` ASC),
  CONSTRAINT `fk_Prüfungen_Unterrichtsstunde1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `ecbook_db`.`unterrichtsstunde` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
