-- MySQL Script generated by MySQL Workbench
-- 03/31/15 06:56:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecbookdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecbookdb` ;

-- -----------------------------------------------------
-- Schema ecbookdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecbookdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_estonian_ci ;
USE `ecbookdb` ;

-- -----------------------------------------------------
-- Table `ecbookdb`.`Benutzergruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Benutzergruppe` (
  `bg_id` INT NOT NULL,
  `bg_name` VARCHAR(45) NULL,
  PRIMARY KEY (`bg_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Person` (
  `p_nachname` VARCHAR(45) NOT NULL,
  `p_vorname` VARCHAR(45) NOT NULL,
  `p_geburtsdatum` DATE NOT NULL,
  `p_wohnort` VARCHAR(45) NULL,
  `p_plz` VARCHAR(45) NULL,
  `p_ort` VARCHAR(45) NULL,
  `p_wohnadresse` VARCHAR(45) NULL,
  `p_telefonnummer` VARCHAR(45) NULL,
  `p_l_benutzername` VARCHAR(45) NOT NULL,
  `p_l_passwort` VARCHAR(45) NOT NULL,
  `bg_id` INT NOT NULL,
  PRIMARY KEY (`p_nachname`, `p_vorname`, `p_geburtsdatum`),
  INDEX `fk_Person_Benutzergruppe1_idx` (`bg_id` ASC),
  CONSTRAINT `fk_Person_Benutzergruppe1`
    FOREIGN KEY (`bg_id`)
    REFERENCES `ecbookdb`.`Benutzergruppe` (`bg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Lehrer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Lehrer` (
  `l_lehrerid` INT NOT NULL,
  `l_istklassenvorstand` TINYINT(1) NOT NULL,
  `l_nachname` VARCHAR(45) NOT NULL,
  `l_vorname` VARCHAR(45) NOT NULL,
  `l_geburtsdatum` DATE NOT NULL,
  PRIMARY KEY (`l_lehrerid`),
  INDEX `fk_Lehrer_Person1_idx` (`l_nachname` ASC, `l_vorname` ASC, `l_geburtsdatum` ASC),
  CONSTRAINT `fk_Lehrer_Person1`
    FOREIGN KEY (`l_nachname` , `l_vorname` , `l_geburtsdatum`)
    REFERENCES `ecbookdb`.`Person` (`p_nachname` , `p_vorname` , `p_geburtsdatum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Abteilung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Abteilung` (
  `abt_bezeichnung` VARCHAR(45) NOT NULL,
  `abt_kuerzel` VARCHAR(45) NOT NULL,
  `abt_vorstand` VARCHAR(45) NULL,
  `l_lehrerid` INT NOT NULL,
  PRIMARY KEY (`abt_bezeichnung`),
  INDEX `fk_Abteilung_Lehrer1_idx` (`l_lehrerid` ASC),
  CONSTRAINT `fk_Abteilung_Lehrer1`
    FOREIGN KEY (`l_lehrerid`)
    REFERENCES `ecbookdb`.`Lehrer` (`l_lehrerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Schulform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Schulform` (
  `schf_id` INT NOT NULL,
  `schf_zweig` VARCHAR(45) NULL,
  `schf_modulanforderung` TINYINT(1) NOT NULL,
  PRIMARY KEY (`schf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Klasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Klasse` (
  `k_name` VARCHAR(45) NOT NULL,
  `k_jahrgang` VARCHAR(45) NULL,
  `k_abschlussjahr` VARCHAR(45) NULL,
  `k_schueleranzahl` INT NULL,
  `k_abt_bezeichnung` VARCHAR(45) NOT NULL,
  `k_semester` TIMESTAMP(0) NULL,
  `schf_id` INT NOT NULL,
  PRIMARY KEY (`k_name`),
  INDEX `fk_Klasse_Abteilung1_idx` (`k_abt_bezeichnung` ASC),
  INDEX `fk_Klasse_Schulform1_idx` (`schf_id` ASC),
  CONSTRAINT `fk_Klasse_Abteilung1`
    FOREIGN KEY (`k_abt_bezeichnung`)
    REFERENCES `ecbookdb`.`Abteilung` (`abt_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klasse_Schulform1`
    FOREIGN KEY (`schf_id`)
    REFERENCES `ecbookdb`.`Schulform` (`schf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Eltern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Eltern` (
  `e_id` VARCHAR(45) NOT NULL,
  `e_nachname` VARCHAR(45) NOT NULL,
  `e_vorname` VARCHAR(45) NOT NULL,
  `e_geburtsdatum` DATE NOT NULL,
  PRIMARY KEY (`e_id`),
  INDEX `fk_Eltern_Person1_idx` (`e_nachname` ASC, `e_vorname` ASC, `e_geburtsdatum` ASC),
  CONSTRAINT `fk_Eltern_Person1`
    FOREIGN KEY (`e_nachname` , `e_vorname` , `e_geburtsdatum`)
    REFERENCES `ecbookdb`.`Person` (`p_nachname` , `p_vorname` , `p_geburtsdatum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Schueler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Schueler` (
  `s_schuelernummer` INT NOT NULL,
  `s_religionsbekenntnis` VARCHAR(45) NULL,
  `s_istklassensprecher` TINYINT(1) NOT NULL,
  `k_name` VARCHAR(45) NOT NULL,
  `e_id` VARCHAR(45) NULL,
  `s_nachname` VARCHAR(45) NOT NULL,
  `s_vorname` VARCHAR(45) NOT NULL,
  `s_geburtsdatum` DATE NOT NULL,
  PRIMARY KEY (`s_schuelernummer`),
  INDEX `fk_Schueler_Klasse1_idx` (`k_name` ASC),
  INDEX `fk_Schueler_Eltern1_idx` (`e_id` ASC),
  INDEX `fk_Schueler_Person1_idx` (`s_nachname` ASC, `s_vorname` ASC, `s_geburtsdatum` ASC),
  CONSTRAINT `fk_Schueler_Klasse1`
    FOREIGN KEY (`k_name`)
    REFERENCES `ecbookdb`.`Klasse` (`k_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schueler_Eltern1`
    FOREIGN KEY (`e_id`)
    REFERENCES `ecbookdb`.`Eltern` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schueler_Person1`
    FOREIGN KEY (`s_nachname` , `s_vorname` , `s_geburtsdatum`)
    REFERENCES `ecbookdb`.`Person` (`p_nachname` , `p_vorname` , `p_geburtsdatum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Unterrichtsfach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Unterrichtsfach` (
  `uf_bezeichnung` VARCHAR(45) NOT NULL,
  `uf_kurzbezeichnung` VARCHAR(45) NOT NULL,
  `uf_jahrgang` VARCHAR(45) NULL,
  `uf_stundenanzahlprowoche` INT NULL,
  PRIMARY KEY (`uf_bezeichnung`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Fehlstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Fehlstunde` (
  `fs_datum` TIMESTAMP NOT NULL,
  `fs_grund` VARCHAR(45) NOT NULL,
  `s_schuelernummer` INT NOT NULL,
  `uf_bezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fs_datum`),
  INDEX `fk_Fehlstunde_Schueler1_idx` (`s_schuelernummer` ASC),
  INDEX `fk_Fehlstunde_Unterrichtsfach1_idx` (`uf_bezeichnung` ASC),
  CONSTRAINT `fk_Fehlstunde_Schueler1`
    FOREIGN KEY (`s_schuelernummer`)
    REFERENCES `ecbookdb`.`Schueler` (`s_schuelernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fehlstunde_Unterrichtsfach1`
    FOREIGN KEY (`uf_bezeichnung`)
    REFERENCES `ecbookdb`.`Unterrichtsfach` (`uf_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Krankmeldung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Krankmeldung` (
  `km_id` INT NOT NULL,
  `km_datum` TIMESTAMP NULL,
  `km_unterschrift` VARCHAR(45) NULL,
  `s_schuelernummer` INT NOT NULL,
  PRIMARY KEY (`km_id`),
  INDEX `fk_Krankmeldung_Schueler1_idx` (`s_schuelernummer` ASC),
  CONSTRAINT `fk_Krankmeldung_Schueler1`
    FOREIGN KEY (`s_schuelernummer`)
    REFERENCES `ecbookdb`.`Schueler` (`s_schuelernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Schueler_has_Fehlstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Schueler_has_Fehlstunde` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Unterrichtsstunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Unterrichtsstunde` (
  `us_id` INT NOT NULL,
  `us_std_datum` DATE NOT NULL,
  `us_stunde` INT NOT NULL,
  `us_kurzbezeichnung` VARCHAR(45) NOT NULL,
  `us_raum` VARCHAR(45) NOT NULL,
  `us_thema` VARCHAR(45) NULL,
  `k_name` VARCHAR(45) NOT NULL,
  `l_lehrerid` INT NOT NULL,
  `uf_bezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`us_id`),
  INDEX `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1_idx` (`k_name` ASC),
  INDEX `fk_Unterrichtsfach in der Unterrichtsstunde_Lehrer1_idx` (`l_lehrerid` ASC),
  INDEX `fk_Unterrichtsstunde_Unterrichtsfach1_idx` (`uf_bezeichnung` ASC),
  CONSTRAINT `fk_Unterrichtsstunde_has_Unterrichtsfach_Klasse1`
    FOREIGN KEY (`k_name`)
    REFERENCES `ecbookdb`.`Klasse` (`k_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unterrichtsfach in der Unterrichtsstunde_Lehrer1`
    FOREIGN KEY (`l_lehrerid`)
    REFERENCES `ecbookdb`.`Lehrer` (`l_lehrerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unterrichtsstunde_Unterrichtsfach1`
    FOREIGN KEY (`uf_bezeichnung`)
    REFERENCES `ecbookdb`.`Unterrichtsfach` (`uf_bezeichnung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Menu` (
  `m_name` INT NOT NULL,
  `m_url` VARCHAR(45) NULL,
  `m_anzeige` VARCHAR(45) NULL,
  `m_beschreibung` VARCHAR(45) NULL,
  PRIMARY KEY (`m_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecbookdb`.`Prüfungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecbookdb`.`Prüfungen` (
  `p_datum` DATE NOT NULL,
  `p_uhrzeit` VARCHAR(45) NULL,
  `uf_id` INT NOT NULL,
  PRIMARY KEY (`p_datum`),
  INDEX `fk_Prüfungen_Unterrichtsstunde1_idx` (`uf_id` ASC),
  CONSTRAINT `fk_Prüfungen_Unterrichtsstunde1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `ecbookdb`.`Unterrichtsstunde` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
